# Generated by Django 6.0.8 on 2026-08-10 00:42

import django.db.models.deletion
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to=music.models.audio_upload_to)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to=music.models.cover_upload_to)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Length in seconds')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_uploaded'],
                'indexes': [models.Index(fields=['owner', 'title'], name='music_song_owner_i_b08603_idx')],
            },
        ),
    ]
